#define ANDROID
// #define IPHONE

#define PMDIMAGESIZE 19800
#define PMDREQUESTSIZE 512
#define PMDNUMCOLS 165
#define PMDNUMROWS 120
#define PMD_INVALID_DISTANCE -1000
#define PMD_MAX_DISTANCE 1.0f
#ifdef ANDROID
#define PMD_MAX_PHONE_DISTANCE 0.22f
#else
#define PMD_MAX_PHONE_DISTANCE 0.2f
#endif
#define PMD_MAX_FINGERS 2